### ISSUE TITLE
Add Keybinding Documentation

### ISSUE THREAD

**Issue by ChiragGhanshani** [project-renard/curie#104]
Create a table of keybindings for users
- [ ] Create a table of keybindings as user documentation

**Comment by zmughal** [comment]
Here's an example of [documentation from Geany](https://wiki.geany.org/howtos/sorted_keyboard_shortcuts).

**Comment by zmughal** [comment]
Closed by the wiki commit: https://github.com/project-renard/project-renard.github.io/commit/336efd8c23395706fb216e0a849c9dd31f4e8ca5.
