### ISSUE TITLE
Keybindings using GtkBindingSet

### ISSUE THREAD

**Issue by zmughal** [project-renard/curie#116]
See [comments](https://github.com/project-renard/curie/issues/31#issuecomment-222364140) at #31.

**Comment by zmughal** [comment]
To do this, we need signals and to do signals, we need to subclass the Glib objects:
- https://metacpan.org/pod/Glib::Object::Subclass#OVERRIDING-BASE-METHODS
- http://gtk2-perl.sourceforge.net/doc/subclassing_widgets_in_perl.html

**Comment by zmughal** [comment]
Also, it might be useful to use the GTK Inspector to debug events. GTK Inspector is an interface that lets you debug events while the GTK application is running. It is built in to GTK and I put more information in issue #103.

**Comment by zmughal** [comment]
`gtk_binding_set_new` is not available using GIR. See https://github.com/GNOME/gtk/commit/374e76a19dac87676995356f6daacb10f4bb6e36#diff-1592658a45832935e9ad0c9c58dad066R580 and https://wiki.gnome.org/Projects/GObjectIntrospection/Annotations.

It is currently marked as "(skip)".

We will continue to use the `if` statement instead of using signals here because we can not use GtkBindingSet.

In a way, this is a bug against goboject-introspection that is worth returning to when we have time.

**Comment by ChiragGhanshani** [comment]
@zmughal, since we're not going to be using signals, we should probably close this issue off. If the bug gets fixed in the future we can come back to this.

**Comment by zmughal** [comment]
Sure. I will keep note of it on the wiki.
