### ISSUE TITLE
Add a widget/dialog to show PDF metadata

### ISSUE THREAD

**Issue by zmughal** [project-renard/curie#13]
See:
`pdfinfo`:
```shell
$ pdfinfo test-data/PDF/Adobe/pdf_reference_1-7.pdf
Title:          PDF Reference, version 1.7
Subject:        Adobe Portable Document Format (PDF)
Author:         Adobe Systems Incorporated
Creator:        FrameMaker 7.2
Producer:       Acrobat Distiller 7.0.5 (Windows)
CreationDate:   Tue Oct 17 03:10:20 2006 CDT
ModDate:        Sat Nov 18 17:40:43 2006 CST
Tagged:         yes
UserProperties: no
Suspects:       no
Form:           AcroForm
JavaScript:     no
Pages:          1310
Encrypted:      no
Page size:      531 x 666 pts
Page rot:       0
File size:      32472771 bytes
Optimized:      yes
PDF version:    1.6
```

Foxit:
![foxitreader_2017-05-13_17-02-04](https://cloud.githubusercontent.com/assets/94489/26029578/e353db38-37fd-11e7-8b74-3eaef9c9a5ad.png)

Adobe Acrobat Reader:
![acrord32_2017-05-13_17-03-09](https://cloud.githubusercontent.com/assets/94489/26029587/10b984b0-37fe-11e7-87c8-77c2947e4259.png)

---

`mutool`

```shell
mutool show pdf_reference_1-7.pdf $(mutool show pdf_reference_1-7.pdf grep | grep 'Author(' | cut -d: -f2 | tail -1)
109959 0 obj
<<
  /CreationDate (D:20061017081020Z)
  /Subject (Adobe Portable Document Format \(PDF\))
  /Author (Adobe Systems Incorporated)
  /Creator (FrameMaker 7.2)
  /Producer (Acrobat Distiller 7.0.5 \(Windows\))
  /ModDate (D:20061118211043-02'30')
  /Title (PDF Reference, version 1.7)
>>
endobj
```

Note that `\( ->(` and `\251 -> ©` (which is ordinal 251 in octal). More info about escaping objects is on page 54 of the PDF reference:

![foxitreader_2017-05-13_17-21-32](https://cloud.githubusercontent.com/assets/94489/26029668/9fd8a714-3800-11e7-80ba-01a9ae0d8053.png)

**Comment by zmughal** [comment]
@helenbach, I updated the issue with more info about the metadata parsing. Let me know if you have any questions.

**Comment by helenbach** [comment]
I started with designing the actual UI for this feature. It's not the best looking right now and it's not complete either, but I'd like to render it and populate it with data. I'll modify it as I work on it until it's good enough, but I don't actually know how to render it. Is there a rendering utility as part of curie, or is there a specific series of Gtk functions I need to call?

**Comment by zmughal** [comment]
@helenbach, if you've got a Glade file, you can use the roles:

```perl
with qw(
	Renard::Curie::Component::Role::FromBuilder
	Renard::Curie::Component::Role::UIFileFromPackageName
);
```
to load the Glade file.

An example is [LogWindow.pm](https://github.com/project-renard/curie/blob/v0.002/lib/Renard/Curie/Component/LogWindow.pm) which loads [LogWindow.glade](https://github.com/project-renard/curie/blob/v0.002/lib/Renard/Curie/Component/LogWindow.glade) from the same directory.

Note that you will need to call `->show_all` on the toplevel widget like with the [`show_log_window`](https://github.com/project-renard/curie/blob/v0.002/lib/Renard/Curie/Component/LogWindow.pm#L66) method.

**Comment by zmughal** [comment]
@helenbach, I'm looking ahead at what you might want to do and you'll also want to look at the `Renard::Curie::Component::Role::HasParentApp` role. See how it is used with some of the other components.

**Comment by zmughal** [comment]
@helenbach, any progress?
