### ISSUE TITLE
Zoom level with spin button

### ISSUE THREAD

**Issue by zmughal** [project-renard/curie#144]
- https://developer.gnome.org/gtk3/stable/GtkSpinButton.html
- https://github.com/project-renard/curie/blob/master/lib/Renard/Curie/Data/PDF.pm

Note: `$resolution = $zoom * 72`, http://ghostscript.com/pipermail/gs-cvs/2016-March/019533.html, https://www.mankier.com/1/mutool#Draw (`mutool -r $resolution ...`)
- https://github.com/project-renard/curie/blob/master/lib/Renard/Curie/Model/Document/PDF.pm

`:$zoom_level parameter = 1.0`
- Change callback to draw signal https://github.com/project-renard/curie/blob/master/lib/Renard/Curie/Component/PageDrawingArea.pm

**Comment by zmughal** [comment]
Related #14, #15.

**Comment by zmughal** [comment]
@helenbach, you want to take this over?

**Comment by helenbach** [comment]
sure

**Comment by zmughal** [comment]
I'm moving this forward. Trying to get to v0.004 as quickly as possible.

**Comment by zmughal** [comment]
Spin button component is not appropriate for this feature. It also takes up an unreasonable amount of space. Closing.
