### ISSUE TITLE
Show Number of Pages in Document

### ISSUE THREAD

**Issue by ChiragGhanshani** [project-renard/curie#21]
When opening a document, it should show how many pages are in the document next to the page entry field.

**Comment by zmughal** [comment]
@StayerX, would you like to work on this?

**Comment by zmughal** [comment]
@StayerX, need a second pair of eyes on this issue?

**Comment by StayerX** [comment]
Here is the pull request: https://github.com/project-renard/curie/pull/43

**Comment by zmughal** [comment]
Closed by #43.
