### ISSUE TITLE
Bug: page navigation bar behaviour

### ISSUE THREAD

**Issue by StayerX** [project-renard/curie#22]
- [x] 1. When we are at the last page of a document/file the forward button should be disabled. In a similar fashion, when we are at the beginning of a file we should not be able to move backwards.
- [x] 2. Page number entry does not display anything on open.
- [x] 3. Page number entry does goes to 0 and goes to (#pages+1) with forward and backwards.

**Comment by zmughal** [comment]
I believe (2) and (3) have been fixed in the refactoring in #24.

**Comment by zmughal** [comment]
@StayerX, if you haven't started, you might want to make the changes based off the now merged #24.

**Comment by ChiragGhanshani** [comment]
I'll work on disabling the forward and backward buttons when at the end/start of the pdf.

**Comment by zmughal** [comment]
@ChiragGhanshani, had any progress on this?

**Comment by zmughal** [comment]
First item is closed by PR #37.
