### ISSUE TITLE
Turn the PNG data from mudraw into Cairo Image Surface in memory

### ISSUE THREAD

**Issue by zmughal** [project-renard/curie#25]
Should be able to create an image surface from the PNG data without using any intermediate files.

**Comment by StayerX** [comment]
Even when we support copy and paste we will be visualizing a png? Is that the best approach and will it support zoom etc?

**Comment by zmughal** [comment]
Yes, we have to draw to an image buffer. The way copy and paste works is by having a hidden layer and mapping a clipping area to the text inside that area.

Zoom is supported by rendering at a different resolution.

**Comment by zmughal** [comment]
A patch for this is at https://github.com/project-renard/curie/issues/30.

**Comment by zmughal** [comment]
Closed by https://github.com/project-renard/curie/pull/30
