### ISSUE TITLE
Generate menus

### ISSUE THREAD

**Issue by zmughal** [project-renard/curie#29]
We need menus because buttons will clutter the UI.
- [x] File →  Open
- [x] File → Recent (submenu)
- [x] File → Quit
- [x] View → Continuous (toggle)
- [x] View → Page mode→Single
- [x] View → Page mode → Facing → First page center
- [x] View → Page mode → Facing → First page right
- [x] View → Page mode → Facing → First page left
- [x] Help → About

**Comment by StayerX** [comment]
This is something I wan to discuss. There so many different menues.

**Comment by zmughal** [comment]
This is where I especially want to survey other readers.

**Comment by StayerX** [comment]
Acrobat DC viewer
![curie-dcreader](https://cloud.githubusercontent.com/assets/11931609/13817781/6439a54a-eb8b-11e5-9bb8-1b7486968fc4.png)
![curie-dcreader-tools](https://cloud.githubusercontent.com/assets/11931609/13817779/64330352-eb8b-11e5-8611-dfd3f44dcf38.png)
![curie-dcreader-openeddoc](https://cloud.githubusercontent.com/assets/11931609/13817780/64374278-eb8b-11e5-84f9-8a9bdd23216c.png)

**Comment by zmughal** [comment]
@StayerX, these are the Adobe PDF screenshots you made.

**Comment by zmughal** [comment]
I created a table of the menus for Evince. I will fill in the descriptions later https://project-renard.github.io/doc/survey/tool/evince/.

**Comment by zmughal** [comment]
<del>TODO: turn list in issue into checklist</del> DONE
