### ISSUE TITLE
Add keybindings for navigation

### ISSUE THREAD

**Issue by zmughal** [project-renard/curie#31]
- [x] PgDown: next page
- [x] PgUp: previous page
- [x] Up/Down/Left/Right arrow keys: control scrolling

**Comment by zmughal** [comment]
To control scrolling, we need to modify the value of the GtkAdjustment on the GtkScrolledWindow. See [this](http://stackoverflow.com/questions/5218948/how-to-auto-scroll-a-gtk-scrolledwindow) for an example.

**Comment by ChiragGhanshani** [comment]
@zmughal checkout the pull request

**Comment by zmughal** [comment]
I am now looking more closely at how bindings in Gtk are done. Perhaps our problem can be solved if we do something using [GtkBindingSet](https://developer.gnome.org/gtk3/stable/gtk3-Bindings.html). Here is an [example from Gimp](https://github.com/GNOME/gimp/blob/0d8b8c2f99779833bb90ba1ee01685a814c9cb7e/modules/gimpcolorwheel.c#L186) and an [example from medit](https://github.com/thioshp/medit_sources/blob/7a4f4791a2757673ee9fe44ba1de10d61dfcc736/moo/mooedit/mootextview.c).

That's how the example from the issue you linked in #105 does the following to add Mac-specific keybindngs with an rc file like

```
binding "gtk-mac-alt-arrows"
{
  bind "<alt>Right"           { "move-cursor" (words, 1, 0) }
  bind "<alt>KP_Right"        { "move-cursor" (words, 1, 0) }
  bind "<alt>Left"            { "move-cursor" (words, -1, 0) }
  bind "<alt>KP_Left"         { "move-cursor" (words, -1, 0) }
  bind "<shift><alt>Right"    { "move-cursor" (words, 1, 1) }
  bind "<shift><alt>KP_Right" { "move-cursor" (words, 1, 1) }
  bind "<shift><alt>Left"     { "move-cursor" (words, -1, 1) }
  bind "<shift><alt>KP_Left"  { "move-cursor" (words, -1, 1) }
}
```

I'll find out more later.

**Comment by zmughal** [comment]
> 02:01:47 [sivoais] Gtk has this built-in way of handling keybindings as signals
> 02:02:21 [sivoais] for example, a scrolling keybinding might want to emit a singal to the GtkScrolledWindow
> 02:02:47 [sivoais] and that signal handles the whole horizontal/vertical increment/decrement
> 02:02:49 [sivoais] https://developer.gnome.org/gtk3/stable/GtkScrolledWindow.html#GtkScrolledWindow-scroll-child
> 02:03:28 [sivoais] "scroll-child" signal takes parameters that tell it how much to scroll and which scrollbar to use
> 02:04:05 [sivoais] I don't know how to implement that yet, but I have a feeling that if we do it the right way like this, it will work on Mac.
> 02:04:45 [sivoais] because tools like Inkscape and GIMP work on Mac already and they use this kind of approach
> 02:05:04 [sivoais] plus, it will allow use to use keybindings that make more sense on the given system
> 02:05:17 [sivoais] Win/Linux: Ctrl+C for copy, Mac: Cmd+C for copy

**Comment by zmughal** [comment]
Docs for Gtk2::BindingSet

http://gtk2-perl.sourceforge.net/doc/pod/Gtk2/BindingSet.html
https://metacpan.org/source/XAOC/Gtk2-1.2498/t/GtkBindings.t

**Comment by zmughal** [comment]
@StayerX, remember how you mentioned that it is possible to have [Vi keys in Gtk applications](http://vim.wikia.com/wiki/Vi_key_bindings_in_gtk)? This works the same way.
