### ISSUE TITLE
Look into GTK+ icon and color theming

### ISSUE THREAD

**Issue by zmughal** [project-renard/curie#32]
The built-in icons are not very modern and the buttons are a little large.

**Comment by StayerX** [comment]
From Zaki, for the loading of the images.
https://developer.gnome.org/gtk3/stable/GtkImage.html
https://developer.gnome.org/gtk3/stable/GtkIconTheme.html

**Comment by zmughal** [comment]
To move this forward, we might want to look at what a modern document reader uses for icons. What do you think?

**Comment by StayerX** [comment]
Yes, I suggest we look into what slack has done and intellij. Right now intellij is one of the best tools out there.
They have combined proper text menu, with an  icons bar with a full screen settings menu.

The icons should have the essential.

Furthermore they have done context menu: at the drawing are allowed: a
At the x area: allowed b

Finally we can have multiple terminals integration at the bottom of the page, switchable with one click.

Here is a screen shot showing the many levels of human interaction:
![intellij_multiple_level_usage](https://cloud.githubusercontent.com/assets/11931609/15453528/2574d0c2-2011-11e6-9701-954e6c76cb64.png)

Here is a screen shot of the settings:
![intellij_settings_panel](https://cloud.githubusercontent.com/assets/11931609/15453527/251dfe8c-2011-11e6-9079-141416088cdf.png)

**Comment by zmughal** [comment]
https://developer.gnome.org/integration-guide/stable/icons.html.en

Also, look at themes in resource files http://ometer.com/gtk-colors.html

http://gnome-look.org/?xcontentmode=121

http://gnome-look.org/index.php?xcontentmode=166

https://design.google.com/icons/

http://www.hongkiat.com/blog/google-apple-microsoft-flat-design/

https://github.com/numixproject/numix-gtk-theme

https://numixproject.org/

https://github.com/numixproject/numix-icon-theme/blob/master/Numix/64/actions/default-document-open.svg

https://github.com/numixproject/numix-icon-theme/blob/master/Numix/64/actions/go-next.svg

This might require creating a new repository which builds everything together.

http://www.hongkiat.com/blog/google-apple-microsoft-flat-design/

https://blogs.gnome.org/mclasen/2014/05/06/tweaking-a-the-gtk-theme-using-css/

"Firebug but for GTK+ applications" https://github.com/chipx86/gtkparasite

**Comment by zmughal** [comment]
Also, look at themes in resource files <http://ometer.com/gtk-colors.html>

**Comment by zmughal** [comment]
http://gnome-look.org/?xcontentmode=121

**Comment by zmughal** [comment]
http://gnome-look.org/index.php?xcontentmode=166

**Comment by zmughal** [comment]
https://design.google.com/icons/

**Comment by zmughal** [comment]
http://www.hongkiat.com/blog/google-apple-microsoft-flat-design/

**Comment by zmughal** [comment]
https://github.com/numixproject/numix-gtk-theme

https://numixproject.org/

**Comment by zmughal** [comment]
This might require creating a new repository which builds everything together.

**Comment by zmughal** [comment]
https://blogs.gnome.org/mclasen/2014/05/06/tweaking-a-the-gtk-theme-using-css/

"Firebug but for GTK+ applications" https://github.com/chipx86/gtkparasite

**Comment by zmughal** [comment]
Resources for design of open source projects:

http://opensourcedesign.net/
http://ura.al/

**Comment by zmughal** [comment]
It might be useful to look at the GTK inspector https://github.com/project-renard/curie/issues/103.

**Comment by zmughal** [comment]
GTK_DEBUG=interactive ./bin/curie.pl

**Comment by zmughal** [comment]
http://customize.org/gtk/themes/49983

**Comment by zmughal** [comment]
https://awesome.naquadah.org/wiki/Customizing_GTK_Apps

**Comment by zmughal** [comment]
https://wiki.archlinux.org/index.php/GTK%2B

**Comment by zmughal** [comment]
![office-20161](https://cloud.githubusercontent.com/assets/94489/16701450/7e4f4752-4525-11e6-89b0-b5b49b461b98.png)

**Comment by zmughal** [comment]
Using
- theme https://github.com/nana-4/Flat-Plat (GPL)
- icon theme https://github.com/horst3180/arc-icon-theme (GPLv3)

![perl_2016-10-14_10-12-15](https://cloud.githubusercontent.com/assets/94489/19392531/c1a6674c-91f6-11e6-96b3-f046a096e130.png)

**Comment by zmughal** [comment]
Default
- theme: Adwaita
- icon theme: Adwaita

![perl_2016-10-14_10-16-25](https://cloud.githubusercontent.com/assets/94489/19392657/5439a3f8-91f7-11e6-9f54-e19c280370ce.png)

**Comment by zmughal** [comment]
```shell
for r in build-theme-flat-plat build-icon-theme-arc; do mkdir $r; ( cd $r ; git hub repo-new project-renard-build/$r ; git clone --recursive git@github.com:project-renard-build/$r.git ); done
cd $P/build-theme-flat-plat/build-theme-flat-plat/
git st
git submodule add https://github.com/nana-4/Flat-Plat.git
git st
git ci -m 'Add Flat-Plat submodule'
git push -u origin master
cd $P/build-icon-theme-arc/build-icon-theme-arc/
git submodule add https://github.com/horst3180/arc-icon-theme.git
git ci -m 'Add Arc icon theme submodule'
git push -u origin master

```
