### ISSUE TITLE
The status bar is too wide

### ISSUE THREAD

**Issue by StayerX** [project-renard/curie#40]
- [ ] 1. We should reduce the thickness of the bar
- [ ] 2. Discuss possible functionalities such as page info, zoom level, zoom button (see review of pdf viewers as a starting point [link-should-be-added-here])

![glade-status-bar](https://cloud.githubusercontent.com/assets/11931609/13900874/7b4ab75e-ee08-11e5-9b9b-b5094dbf4f0a.png)

**Comment by zmughal** [comment]
I like this idea!

**Comment by StayerX** [comment]
This has been implemented at PR #53.

**Comment by zmughal** [comment]
Fix for now is to remove the status bar completely.
