### ISSUE TITLE
Split the buttons for the PageDrawingComponent outside main Glade file

### ISSUE THREAD

**Issue by zmughal** [project-renard/curie#61]
These need to be associated with the particular document.

**Comment by StayerX** [comment]
I want to take this one, if OK with you.

**Comment by zmughal** [comment]
If we do this, we need to figure out how to make the components extend `Gtk3::Widget`. There is a module on CPAN that does this very well: [`Gtk3::SimpleList`](http://p3rl.org/Gtk3::SimpleList).

**Comment by zmughal** [comment]
I'm going to take over this. I will make it work along with #69.

**Comment by zmughal** [comment]
PR at #72.

**Comment by zmughal** [comment]
Closed by #72.
