### ISSUE TITLE
Gtk3 test_widget_send_key does not work

### ISSUE THREAD

**Issue by ChiragGhanshani** [project-renard/curie#64]
We need to figure out an alternative solution

**Comment by zmughal** [comment]
See issues #31 and PR #52.

**Comment by zmughal** [comment]
Can confirm that this is an issue. See comment in `key_press` function for [WWW::WebKit](https://metacpan.org/source/NINE/WWW-WebKit-0.07/lib/WWW/WebKit.pm#L651-676) and the author's [mailing list message](https://mail.gnome.org/archives/gtk-perl-list/2011-November/msg00047.html).

Alternative is to use X11::Xlib (for XTest), but that limits where it can be used.

**Comment by zmughal** [comment]
Looks like [the solution](https://github.com/project-renard/curie/blob/c829eaa062d42f86089928fc2350e33ef701037e/t/Renard/Curie/Component/KeyBindings.t#L51-L53) was to use

``` perl
    my $event = Gtk3::Gdk::Event->new('key-press');
    $event->keyval($key);
    $app->window->signal_emit( key_press_event => $event );
```
