### ISSUE TITLE
Add a text field for selecting page by number

### ISSUE THREAD

**Issue by zmughal** [project-renard/curie#8]
@ChiragGhanshani, could you add a new text area widget to the `simple-gui` branch (PR https://github.com/project-renard/curie/pull/6) that is between the back and forward buttons which
- shows _the current page number_ and _the number of pages_
- and when the user enters a page in the text area, it should _set the current page number_ to whatever was entered

Something like the following interface from xpdf:
![xpdf typefaces pdf_166](https://cloud.githubusercontent.com/assets/94489/12922913/0aa37ecc-cf19-11e5-9125-daf1303ad96b.png)

Create a new branch off the `simple-gui` branch and open a pull request for your change.

If you get stuck, please ask.

**Comment by zmughal** [comment]
@ChiragGhanshani, if you have anything in progress, you can still push to a branch and make a pull request. You don't need to have it complete before you make the pull request nor does everything need to be in a single commit.

**Comment by ChiragGhanshani** [comment]
Feature has been added in:
https://github.com/project-renard/curie/pull/20

**Comment by zmughal** [comment]
Closed by #20 and #6.
