### ISSUE TITLE
Make Travis CI Tests for Mac OS X

### ISSUE THREAD

**Issue by ChiragGhanshani** [project-renard/curie#95]
Connects to https://github.com/project-renard/curie/issues/109

https://github.com/project-renard/curie/issues/102

**Comment by zmughal** [comment]
- [documentation about the OS X build environment](https://docs.travis-ci.com/user/osx-ci-environment/)
- In the `.travis.yml`, you have to set the following [config param](https://docs.travis-ci.com/user/osx-ci-environment/):

``` yaml
os:
  - linux
  - osx
```

**Comment by zmughal** [comment]
See this: https://docs.travis-ci.com/user/multi-os/
